<?php
/**
 * Mazala QPay Fixtures Data
 * 
 * Embedded reference data from qPay API documentation
 * Auto-generated from QPayAPIv2.xlsx
 * 
 * @package MazalaQPay
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Provides static reference data for qPay integration
 */
class MZQPay_Fixtures_Data {

    /**
     * Bank codes with EN/MN names (21 banks)
     * @return array
     */
    public static function get_bank_data() {
        return array(
            '010000' => array('code' => '010000', 'name_en' => 'Bank of Mongolia', 'name_mn' => 'Монгол банк'),
            '020000' => array('code' => '020000', 'name_en' => 'Capital bank', 'name_mn' => 'Капитал банк'),
            '040000' => array('code' => '040000', 'name_en' => 'Trade and Development bank of Mongolia', 'name_mn' => 'Худалдаа хөгжлийн банк'),
            '050000' => array('code' => '050000', 'name_en' => 'Khan bank', 'name_mn' => 'Хаан банк'),
            '150000' => array('code' => '150000', 'name_en' => 'Golomt bank', 'name_mn' => 'Голомт банк'),
            '190000' => array('code' => '190000', 'name_en' => 'Trans bank', 'name_mn' => 'Тээвэр хөгжлийн банк'),
            '210000' => array('code' => '210000', 'name_en' => 'Arig bank', 'name_mn' => 'Ариг банк'),
            '220000' => array('code' => '220000', 'name_en' => 'Credit bank', 'name_mn' => 'Кредит банк'),
            '290000' => array('code' => '290000', 'name_en' => 'NIB bank', 'name_mn' => 'ҮХО банк'),
            '300000' => array('code' => '300000', 'name_en' => 'Capitron bank', 'name_mn' => 'Капитрон банк'),
            '320000' => array('code' => '320000', 'name_en' => 'Xac bank', 'name_mn' => 'Хас банк'),
            '330000' => array('code' => '330000', 'name_en' => 'Chingiskhan bank', 'name_mn' => 'Чингисхаан банк'),
            '340000' => array('code' => '340000', 'name_en' => 'State bank', 'name_mn' => 'Төрийн банк'),
            '360000' => array('code' => '360000', 'name_en' => 'National Development bank', 'name_mn' => 'Хөгжлийн банк'),
            '380000' => array('code' => '380000', 'name_en' => 'Bogd bank', 'name_mn' => 'Богд банк'),
            '900000' => array('code' => '900000', 'name_en' => 'State fund', 'name_mn' => 'Төрийн сан'),
            '500000' => array('code' => '500000', 'name_en' => 'Mobi Finance', 'name_mn' => 'Мобифинанс'),
            '390000' => array('code' => '390000', 'name_en' => 'M bank', 'name_mn' => 'М банк'),
            '993000' => array('code' => '993000', 'name_en' => 'Invescore', 'name_mn' => 'Инвэскор ББСБ'),
            '100000' => array('code' => '100000', 'name_en' => 'Test bank', 'name_mn' => 'Тест банк'),
            'TOKI' => array('code' => 'TOKI', 'name_en' => 'Toki app', 'name_mn' => 'Токи'),
        );
    }

    /**
     * Supported currency codes (6 currencies)
     * @return array
     */
    public static function get_currency_data() {
        return array(
            'MNT' => array('code' => 'MNT', 'name' => 'Төгрөг'),
            'USD' => array('code' => 'USD', 'name' => 'Америк доллар'),
            'CNY' => array('code' => 'CNY', 'name' => 'Юань'),
            'JPY' => array('code' => 'JPY', 'name' => 'Иен'),
            'RUB' => array('code' => 'RUB', 'name' => 'Рубль'),
            'EUR' => array('code' => 'EUR', 'name' => 'Евро'),
        );
    }

    /**
     * HTTP status codes
     * @return array
     */
    public static function get_http_codes() {
        return array(
            '200' => array('code' => '200', 'key' => 'SUCCESS', 'message_en' => 'Success', 'message_mn' => 'Амжилттай'),
            '400' => array('code' => '400', 'key' => 'VALIDATION_ERROR', 'message_en' => 'Validation Error', 'message_mn' => 'Параметр буруу илгээсэн үед гарах алдаа'),
            '401' => array('code' => '401', 'key' => 'UNAUTHORIZED_ERROR', 'message_en' => 'Unauthorized', 'message_mn' => 'Нэвтрэлгүй дуудсан үед гарах алдаа'),
            '403' => array('code' => '403', 'key' => 'FORBIDDEN_ERROR', 'message_en' => 'Forbidden', 'message_mn' => 'Хандах эрх хүрээгүй үед гарах алдаа'),
            '409' => array('code' => '409', 'key' => 'UNIQUE_ERROR', 'message_en' => 'Duplicate Error', 'message_mn' => 'Бүртгэлийн мэдээлэл давхацсан үед гарах алдаа'),
            '422' => array('code' => '422', 'key' => 'NOT_FOUND_ERROR', 'message_en' => 'Not Found', 'message_mn' => 'Мэдээлэл олдоогүй үед гарах алдаа'),
            '500' => array('code' => '500', 'key' => 'INTERNAL_ERROR', 'message_en' => 'Internal Error', 'message_mn' => 'Системийн дотоод алдаа'),
        );
    }

    /**
     * Error messages with bilingual support (61 codes)
     * @return array
     */
    public static function get_error_data() {
        return array(
            'ACCOUNT_BANK_DUPLICATED' => array('key' => 'ACCOUNT_BANK_DUPLICATED', 'message_mn' => 'Банкны данс давхацсан байна', 'message_en' => 'Bank account is already registered!'),
            'ACCOUNT_SELECTION_INVALID' => array('key' => 'ACCOUNT_SELECTION_INVALID', 'message_mn' => 'Дансны сонголт буруу', 'message_en' => 'Account selection is invalid!'),
            'AUTHENTICATION_FAILED' => array('key' => 'AUTHENTICATION_FAILED', 'message_mn' => 'Нэвтрэх нэр	 нууц үг буруу', 'message_en' => 'Your username and password are wrong!'),
            'BANK_ACCOUNT_NOTFOUND' => array('key' => 'BANK_ACCOUNT_NOTFOUND', 'message_mn' => 'Банкны данс олдсонгүй', 'message_en' => 'Bank account is not found!'),
            'BANK_MCC_ALREADY_ADDED' => array('key' => 'BANK_MCC_ALREADY_ADDED', 'message_mn' => 'Банкны MCC кодыг нэмчихсэн байна', 'message_en' => 'Bank MCC is already added!'),
            'BANK_MCC_NOT_FOUND' => array('key' => 'BANK_MCC_NOT_FOUND', 'message_mn' => 'Банкны MCC код олдсонгүй', 'message_en' => 'Bank MCC is not found!'),
            'CARD_TERMINAL_NOTFOUND' => array('key' => 'CARD_TERMINAL_NOTFOUND', 'message_mn' => 'Картын терминал бүртгэлгүй байна', 'message_en' => 'Card terminal is not registered!'),
            'CLIENT_NOTFOUND' => array('key' => 'CLIENT_NOTFOUND', 'message_mn' => 'Клиентийн бүртгэл олдсонгүй', 'message_en' => 'Client is not registered!'),
            'CLIENT_USERNAME_DUPLICATED' => array('key' => 'CLIENT_USERNAME_DUPLICATED', 'message_mn' => 'Клиентийн хэрэглэгчийн нэр давхацсан', 'message_en' => 'Client username is already exist!'),
            'CUSTOMER_DUPLICATE' => array('key' => 'CUSTOMER_DUPLICATE', 'message_mn' => 'Харилцагчийн регистрийн дугаар давхацсан байна!', 'message_en' => 'Customer register duplicated!'),
            'CUSTOMER_NOTFOUND' => array('key' => 'CUSTOMER_NOTFOUND', 'message_mn' => 'Харилцагч бүртгэгдээгүй байна!', 'message_en' => 'Customer not registered!'),
            'CUSTOMER_REGISTER_INVALID' => array('key' => 'CUSTOMER_REGISTER_INVALID', 'message_mn' => 'Харилцагч регистрийн дугаар байна!', 'message_en' => 'Customer register is wrong!'),
            'EBARIMT_CANCEL_NOTSUPPERDED' => array('key' => 'EBARIMT_CANCEL_NOTSUPPERDED', 'message_mn' => 'qPay үйлчилгээ и-баримтыг цуцлах боломжгүй байна.', 'message_en' => 'qPay service eBarimt unregister function not supported'),
            'EBARIMT_NOT_REGISTERED' => array('key' => 'EBARIMT_NOT_REGISTERED', 'message_mn' => 'и-Баримт үүсээгүй байна.', 'message_en' => 'eBarimt not registered!'),
            'EBARIMT_QR_CODE_INVALID' => array('key' => 'EBARIMT_QR_CODE_INVALID', 'message_mn' => 'Төлбөр хүлээн авагчийн илгээсэн и-баримт-ын QR код буруу байна.', 'message_en' => 'eBarimt QR code invalid by merchant'),
            'INFORM_NOTFOUND' => array('key' => 'INFORM_NOTFOUND', 'message_mn' => 'Мэдэгдэлийн хаяг олдсонгүй', 'message_en' => 'Inform is not found!'),
            'INPUT_CODE_REGISTERED' => array('key' => 'INPUT_CODE_REGISTERED', 'message_mn' => 'Input code бүртгэгдсэн байна', 'message_en' => 'Input code is already registered!'),
            'INPUT_NOTFOUND' => array('key' => 'INPUT_NOTFOUND', 'message_mn' => 'Input олдсонгүй', 'message_en' => 'Input is already registered!'),
            'INVALID_AMOUNT' => array('key' => 'INVALID_AMOUNT', 'message_mn' => 'Үнийн дүн буруу', 'message_en' => 'Amount is invalid!'),
            'INVALID_OBJECT_TYPE' => array('key' => 'INVALID_OBJECT_TYPE', 'message_mn' => 'object_type буруу', 'message_en' => 'Object type is invalid!'),
            'INVOICE_ALREADY_CANCELED' => array('key' => 'INVOICE_ALREADY_CANCELED', 'message_mn' => 'Нэхэмжлэл цуцлагдсан байна', 'message_en' => 'Invoice is already cancelled!'),
            'INVOICE_CODE_INVALID' => array('key' => 'INVOICE_CODE_INVALID', 'message_mn' => 'Нэхэмжлэлийн код буруу', 'message_en' => 'Invoice code is wrong!'),
            'INVOICE_CODE_REGISTERED' => array('key' => 'INVOICE_CODE_REGISTERED', 'message_mn' => 'Нэхэмжлэлийн код бүртгэгдсэн байна', 'message_en' => 'Invoice code is already registered!'),
            'INVOICE_LINE_REQUIRED' => array('key' => 'INVOICE_LINE_REQUIRED', 'message_mn' => 'Нэхэмжлэлийн мөр шаардлагатай', 'message_en' => 'Invoice line is required!'),
            'INVOICE_NOTFOUND' => array('key' => 'INVOICE_NOTFOUND', 'message_mn' => 'Нэхэмжлэл олдсонгүй', 'message_en' => 'Invoice is not found!'),
            'INVOICE_PAID' => array('key' => 'INVOICE_PAID', 'message_mn' => 'Нэхэмжлэл төлөгдсөн', 'message_en' => 'Invoice is paid!'),
            'INVOICE_RECEIVER_DATA_ADDRESS_REQUIRED' => array('key' => 'INVOICE_RECEIVER_DATA_ADDRESS_REQUIRED', 'message_mn' => 'Нэхэмжлэл хүлээн авагчийн хаягийн мэдээлэл шаардлагатай', 'message_en' => 'Invoice receiver address is required!'),
            'INVOICE_RECEIVER_DATA_EMAIL_REQUIRED' => array('key' => 'INVOICE_RECEIVER_DATA_EMAIL_REQUIRED', 'message_mn' => 'Нэхэмжлэл хүлээн авагчийн имэйл хаяг шаардлагатай', 'message_en' => 'Invoice receiver email is required!'),
            'INVOICE_RECEIVER_DATA_PHONE_REQUIRED' => array('key' => 'INVOICE_RECEIVER_DATA_PHONE_REQUIRED', 'message_mn' => 'Нэхэмжлэл хүлээн авагчийн утасны дугаар шаардлагатай', 'message_en' => 'Invoice receiver phone is required!'),
            'INVOICE_RECEIVER_DATA_REQUIRED' => array('key' => 'INVOICE_RECEIVER_DATA_REQUIRED', 'message_mn' => 'Нэхэмжлэл хүлээн авагчийн мэдээлэл шаардлагатай', 'message_en' => 'Invoice receiver data is required!'),
            'MAX_AMOUNT_ERR' => array('key' => 'MAX_AMOUNT_ERR', 'message_mn' => 'Үнийн дүн хэт их байна', 'message_en' => 'Amount is over than max value!'),
            'MCC_NOTFOUND' => array('key' => 'MCC_NOTFOUND', 'message_mn' => 'MCC код олдсонгүй', 'message_en' => 'MCC is not found!'),
            'MERCHANT_ALREADY_REGISTERED' => array('key' => 'MERCHANT_ALREADY_REGISTERED', 'message_mn' => 'Мерчантын бүртгэл давхацсан', 'message_en' => 'Merchant is already registered!'),
            'MERCHANT_INACTIVE' => array('key' => 'MERCHANT_INACTIVE', 'message_mn' => 'Мерчант идэвхигүй', 'message_en' => 'Merchant is inactive!'),
            'MERCHANT_NOTFOUND' => array('key' => 'MERCHANT_NOTFOUND', 'message_mn' => 'Мерчант бүртгэлгүй байна', 'message_en' => 'Merchant is not registered!'),
            'MIN_AMOUNT_ERR' => array('key' => 'MIN_AMOUNT_ERR', 'message_mn' => 'Үнийн дүн хэт бага байна', 'message_en' => 'Amount is less than minimum value!'),
            'NO_CREDENDIALS' => array('key' => 'NO_CREDENDIALS', 'message_mn' => 'Хандах эрхгүй байна. Нэвтрэнэ үү.', 'message_en' => 'Your credential is invalid. Please login!'),
            'OBJECT_DATA_ERROR' => array('key' => 'OBJECT_DATA_ERROR', 'message_mn' => 'object_data алдаа', 'message_en' => 'Object data is wrong!'),
            'P2P_TERMINAL_NOTFOUND' => array('key' => 'P2P_TERMINAL_NOTFOUND', 'message_mn' => 'P2P терминал бүртгэлгүй байна', 'message_en' => 'P2P terminal is not registered!'),
            'PAYMENT_ALREADY_CANCELED' => array('key' => 'PAYMENT_ALREADY_CANCELED', 'message_mn' => 'Төлбөр цуцлагдсан байна', 'message_en' => 'Payment is already cancelled!'),
            'PAYMENT_NOT_PAID' => array('key' => 'PAYMENT_NOT_PAID', 'message_mn' => 'Төлбөр төлөлт хийгдээгүй байна', 'message_en' => 'Payment has not paid!'),
            'PAYMENT_NOTFOUND' => array('key' => 'PAYMENT_NOTFOUND', 'message_mn' => 'Төлбөр олдсонгүй', 'message_en' => 'Payment is not found!'),
            'PERMISSION_DENIED' => array('key' => 'PERMISSION_DENIED', 'message_mn' => 'Хандах эрх хүрэхгүй байна', 'message_en' => 'Your access permission is not allowed!'),
            'QRACCOUNT_INACTIVE' => array('key' => 'QRACCOUNT_INACTIVE', 'message_mn' => 'QR данс идэвхигүй', 'message_en' => 'QR account is inactive!'),
            'QRACCOUNT_NOTFOUND' => array('key' => 'QRACCOUNT_NOTFOUND', 'message_mn' => 'QR данс олдсонгүй', 'message_en' => 'QR account is not found!'),
            'QRCODE_NOTFOUND' => array('key' => 'QRCODE_NOTFOUND', 'message_mn' => 'QR код олдсонгүй', 'message_en' => 'QR code is not found!'),
            'QRCODE_USED' => array('key' => 'QRCODE_USED', 'message_mn' => 'QR код ашиглагдаж байна', 'message_en' => 'QR code is already used!'),
            'SENDER_BRANCH_DATA_REQUIRED' => array('key' => 'SENDER_BRANCH_DATA_REQUIRED', 'message_mn' => 'Илгээгчийн салбарын мэдээлэл шаардлагатай', 'message_en' => 'Sender branch data is required!'),
            'TAX_LINE_REQUIRED' => array('key' => 'TAX_LINE_REQUIRED', 'message_mn' => 'Татварын мөр шаардлагатай', 'message_en' => 'Tax line is required!'),
            'TAX_PRODUCT_CODE_REQUIRED' => array('key' => 'TAX_PRODUCT_CODE_REQUIRED', 'message_mn' => 'Татварын бүтээгдэхүүний код шаардлагатай', 'message_en' => 'Tax product code is required!'),
            'TRANSACTION_NOT_APPROVED' => array('key' => 'TRANSACTION_NOT_APPROVED', 'message_mn' => 'Гүйлгээний мөр зөвшөөрөгдөөгүй байна', 'message_en' => 'Transaction line is not approved!'),
            'TRANSACTION_REQUIRED' => array('key' => 'TRANSACTION_REQUIRED', 'message_mn' => 'Гүйлгээний мөр шаардлагатай байна', 'message_en' => 'Transaction line is required!'),
        );
    }

    /**
     * District codes - 506 sub-branches across 30 branches
     * @return array
     */
    public static function get_district_data() {
        return array(
            '1' => array(
                'name' => 'Архангай',
                'code' => '1',
                'sub_branches' => array(
                    '1' => array('name' => 'Их тамир', 'code' => '1', 'full_code' => '101'),
                    '2' => array('name' => 'Чулуут', 'code' => '2', 'full_code' => '102'),
                    '3' => array('name' => 'Хангай', 'code' => '3', 'full_code' => '103'),
                    '4' => array('name' => 'Тариат', 'code' => '4', 'full_code' => '104'),
                    '5' => array('name' => 'Өндөр-Улаан', 'code' => '5', 'full_code' => '105'),
                    '6' => array('name' => 'Эрдэнэмандал', 'code' => '6', 'full_code' => '106'),
                    '7' => array('name' => 'Жаргалант', 'code' => '7', 'full_code' => '107'),
                    '8' => array('name' => 'Цэцэрлэг', 'code' => '8', 'full_code' => '108'),
                    '9' => array('name' => 'Хайрхан', 'code' => '9', 'full_code' => '109'),
                    '10' => array('name' => 'Батцэнгэл', 'code' => '10', 'full_code' => '110'),
                    '11' => array('name' => 'Өлзийт', 'code' => '11', 'full_code' => '111'),
                    '12' => array('name' => 'Өгийнуур', 'code' => '12', 'full_code' => '112'),
                    '13' => array('name' => 'Хашаат', 'code' => '13', 'full_code' => '113'),
                    '14' => array('name' => 'Хотонт', 'code' => '14', 'full_code' => '114'),
                    '15' => array('name' => 'Цэнхэр', 'code' => '15', 'full_code' => '115'),
                    '16' => array('name' => 'Төвшрүүлэх', 'code' => '16', 'full_code' => '116'),
                    '17' => array('name' => 'Булган', 'code' => '17', 'full_code' => '117'),
                    '19' => array('name' => 'Цахир', 'code' => '19', 'full_code' => '119'),
                    '20' => array('name' => 'Эрдэнэбулган', 'code' => '20', 'full_code' => '120'),
                ),
            ),
            '2' => array(
                'name' => 'Баян-Өлгий',
                'code' => '2',
                'sub_branches' => array(
                    '1' => array('name' => 'Алтай', 'code' => '1', 'full_code' => '201'),
                    '2' => array('name' => 'Алтанцөгц', 'code' => '2', 'full_code' => '202'),
                    '3' => array('name' => 'Баяннуур', 'code' => '3', 'full_code' => '203'),
                    '4' => array('name' => 'Бугат', 'code' => '4', 'full_code' => '204'),
                    '5' => array('name' => 'Булган', 'code' => '5', 'full_code' => '205'),
                    '6' => array('name' => 'Буянт', 'code' => '6', 'full_code' => '206'),
                    '7' => array('name' => 'Дэлүүн', 'code' => '7', 'full_code' => '207'),
                    '8' => array('name' => 'Ногооннуур', 'code' => '8', 'full_code' => '208'),
                    '9' => array('name' => 'Сагсай', 'code' => '9', 'full_code' => '209'),
                    '10' => array('name' => 'Толбо', 'code' => '10', 'full_code' => '210'),
                    '11' => array('name' => 'Улаанхус', 'code' => '11', 'full_code' => '211'),
                    '12' => array('name' => 'Цэнгэл', 'code' => '12', 'full_code' => '212'),
                    '14' => array('name' => 'Өлгий', 'code' => '14', 'full_code' => '214'),
                ),
            ),
            '3' => array(
                'name' => 'Баянхонгор',
                'code' => '3',
                'sub_branches' => array(
                    '1' => array('name' => 'Баацагаан', 'code' => '1', 'full_code' => '301'),
                    '2' => array('name' => 'Баянбулаг', 'code' => '2', 'full_code' => '302'),
                    '3' => array('name' => 'Баянговь', 'code' => '3', 'full_code' => '303'),
                    '4' => array('name' => 'Баянлиг', 'code' => '4', 'full_code' => '304'),
                    '5' => array('name' => 'Баян-Овоо', 'code' => '5', 'full_code' => '305'),
                    '6' => array('name' => 'Баян-Өндөр', 'code' => '6', 'full_code' => '306'),
                    '7' => array('name' => 'Баянцагаан', 'code' => '7', 'full_code' => '307'),
                    '8' => array('name' => 'Богд', 'code' => '8', 'full_code' => '308'),
                    '9' => array('name' => 'Бөмбөгөр', 'code' => '9', 'full_code' => '309'),
                    '10' => array('name' => 'Бууцагаан', 'code' => '10', 'full_code' => '310'),
                    '11' => array('name' => 'Галуут', 'code' => '11', 'full_code' => '311'),
                    '12' => array('name' => 'Гурванбулаг', 'code' => '12', 'full_code' => '312'),
                    '13' => array('name' => 'Жаргалант', 'code' => '13', 'full_code' => '313'),
                    '14' => array('name' => 'Жинст', 'code' => '14', 'full_code' => '314'),
                    '15' => array('name' => 'Заг', 'code' => '15', 'full_code' => '315'),
                    '16' => array('name' => 'Өлзийт', 'code' => '16', 'full_code' => '316'),
                    '17' => array('name' => 'Хүрээмарал', 'code' => '17', 'full_code' => '317'),
                    '18' => array('name' => 'Шинэжинст', 'code' => '18', 'full_code' => '318'),
                    '19' => array('name' => 'Эрдэнэцогт', 'code' => '19', 'full_code' => '319'),
                    '20' => array('name' => 'Баянхонгор', 'code' => '20', 'full_code' => '320'),
                ),
            ),
            '4' => array(
                'name' => 'Булган',
                'code' => '4',
                'sub_branches' => array(
                    '1' => array('name' => 'Сайхан', 'code' => '1', 'full_code' => '401'),
                    '2' => array('name' => 'Тэшиг', 'code' => '2', 'full_code' => '402'),
                    '3' => array('name' => 'Хутаг-Өндөр', 'code' => '3', 'full_code' => '403'),
                    '4' => array('name' => 'Баян-Агт', 'code' => '4', 'full_code' => '404'),
                    '5' => array('name' => 'Баяннуур', 'code' => '5', 'full_code' => '405'),
                    '6' => array('name' => 'Бугат', 'code' => '6', 'full_code' => '406'),
                    '7' => array('name' => 'Бүрэгхангай', 'code' => '7', 'full_code' => '407'),
                    '8' => array('name' => 'Гурван Булаг', 'code' => '8', 'full_code' => '408'),
                    '9' => array('name' => 'Дашинчилэн', 'code' => '9', 'full_code' => '409'),
                    '10' => array('name' => 'Могод', 'code' => '10', 'full_code' => '410'),
                    '11' => array('name' => 'Орхон', 'code' => '11', 'full_code' => '411'),
                    '12' => array('name' => 'Сэлэнгэ', 'code' => '12', 'full_code' => '412'),
                    '13' => array('name' => 'Хангал', 'code' => '13', 'full_code' => '413'),
                    '14' => array('name' => 'Рашаант', 'code' => '14', 'full_code' => '414'),
                    '15' => array('name' => 'Хишиг-Өндөр', 'code' => '15', 'full_code' => '415'),
                    '16' => array('name' => 'Булган', 'code' => '16', 'full_code' => '416'),
                    '17' => array('name' => 'Өлзийт', 'code' => '17', 'full_code' => '417'),
                    '18' => array('name' => 'Хялганат', 'code' => '18', 'full_code' => '418'),
                ),
            ),
            '5' => array(
                'name' => 'Говь-Алтай',
                'code' => '5',
                'sub_branches' => array(
                    '1' => array('name' => 'Алтай', 'code' => '1', 'full_code' => '501'),
                    '3' => array('name' => 'Баян-Уул', 'code' => '3', 'full_code' => '503'),
                    '4' => array('name' => 'Бигэр', 'code' => '4', 'full_code' => '504'),
                    '5' => array('name' => 'Бугат', 'code' => '5', 'full_code' => '505'),
                    '6' => array('name' => 'Жаргалан', 'code' => '6', 'full_code' => '506'),
                    '7' => array('name' => 'Дарив', 'code' => '7', 'full_code' => '507'),
                    '8' => array('name' => 'Дэлгэр', 'code' => '8', 'full_code' => '508'),
                    '9' => array('name' => 'Тайшир', 'code' => '9', 'full_code' => '509'),
                    '10' => array('name' => 'Тонхил', 'code' => '10', 'full_code' => '510'),
                    '11' => array('name' => 'Төгрөг', 'code' => '11', 'full_code' => '511'),
                    '12' => array('name' => 'Халиун', 'code' => '12', 'full_code' => '512'),
                    '13' => array('name' => 'Хөхморьт', 'code' => '13', 'full_code' => '513'),
                    '14' => array('name' => 'Цогт', 'code' => '14', 'full_code' => '514'),
                    '15' => array('name' => 'Цээл', 'code' => '15', 'full_code' => '515'),
                    '16' => array('name' => 'Чандмань', 'code' => '16', 'full_code' => '516'),
                    '17' => array('name' => 'Шарга', 'code' => '17', 'full_code' => '517'),
                    '18' => array('name' => 'Эрдэнэ', 'code' => '18', 'full_code' => '518'),
                    '19' => array('name' => 'Есөнбулаг', 'code' => '19', 'full_code' => '519'),
                ),
            ),
            '6' => array(
                'name' => 'Дорноговь',
                'code' => '6',
                'sub_branches' => array(
                    '8' => array('name' => 'Сайхандулаан', 'code' => '8', 'full_code' => '608'),
                    '9' => array('name' => 'Улаанбадрах', 'code' => '9', 'full_code' => '609'),
                    '10' => array('name' => 'Хатанбулаг', 'code' => '10', 'full_code' => '610'),
                    '11' => array('name' => 'Хөвсгөл', 'code' => '11', 'full_code' => '611'),
                    '12' => array('name' => 'Эрдэнэ', 'code' => '12', 'full_code' => '612'),
                    '14' => array('name' => 'Замын-Үүд', 'code' => '14', 'full_code' => '614'),
                    '17' => array('name' => 'Сайншанд', 'code' => '17', 'full_code' => '617'),
                    '1' => array('name' => 'Айраг', 'code' => '1', 'full_code' => '601'),
                    '2' => array('name' => 'Алтанширээ', 'code' => '2', 'full_code' => '602'),
                    '3' => array('name' => 'Даланжаргалан', 'code' => '3', 'full_code' => '603'),
                    '4' => array('name' => 'Дэлгэрэх', 'code' => '4', 'full_code' => '604'),
                    '5' => array('name' => 'Иххэт', 'code' => '5', 'full_code' => '605'),
                    '6' => array('name' => 'Мандах', 'code' => '6', 'full_code' => '606'),
                    '7' => array('name' => 'Өргөн', 'code' => '7', 'full_code' => '607'),
                ),
            ),
            '7' => array(
                'name' => 'Дорнод',
                'code' => '7',
                'sub_branches' => array(
                    '1' => array('name' => 'Баян-Уул', 'code' => '1', 'full_code' => '701'),
                    '2' => array('name' => 'Баяндун', 'code' => '2', 'full_code' => '702'),
                    '3' => array('name' => 'Баянтүмэн', 'code' => '3', 'full_code' => '703'),
                    '4' => array('name' => 'Гурванзагал', 'code' => '4', 'full_code' => '704'),
                    '5' => array('name' => 'Дашбалбар', 'code' => '5', 'full_code' => '705'),
                    '6' => array('name' => 'Матад', 'code' => '6', 'full_code' => '706'),
                    '7' => array('name' => 'Хөлөнбуйр', 'code' => '7', 'full_code' => '707'),
                    '8' => array('name' => 'Булган', 'code' => '8', 'full_code' => '708'),
                    '9' => array('name' => 'Сэргэлэн', 'code' => '9', 'full_code' => '709'),
                    '11' => array('name' => 'Халхгол', 'code' => '11', 'full_code' => '711'),
                    '12' => array('name' => 'Цагаан-Овоо', 'code' => '12', 'full_code' => '712'),
                    '13' => array('name' => 'Чулуунхороот', 'code' => '13', 'full_code' => '713'),
                    '14' => array('name' => 'Чойбалсан', 'code' => '14', 'full_code' => '714'),
                    '15' => array('name' => 'Хэрлэн', 'code' => '15', 'full_code' => '715'),
                ),
            ),
            '8' => array(
                'name' => 'Дундговь',
                'code' => '8',
                'sub_branches' => array(
                    '1' => array('name' => 'Адаацаг', 'code' => '1', 'full_code' => '801'),
                    '2' => array('name' => 'Баянжаргалан', 'code' => '2', 'full_code' => '802'),
                    '3' => array('name' => 'Говь-Угтаал', 'code' => '3', 'full_code' => '803'),
                    '4' => array('name' => 'Дэлгэрцогт', 'code' => '4', 'full_code' => '804'),
                    '5' => array('name' => 'Дэрэн', 'code' => '5', 'full_code' => '805'),
                    '6' => array('name' => 'Гурвансайхан', 'code' => '6', 'full_code' => '806'),
                    '7' => array('name' => 'Дэлгэрхангай', 'code' => '7', 'full_code' => '807'),
                    '8' => array('name' => 'Луус', 'code' => '8', 'full_code' => '808'),
                    '10' => array('name' => 'Сайнцагаан', 'code' => '10', 'full_code' => '810'),
                    '11' => array('name' => 'Сайхан-Овоо', 'code' => '11', 'full_code' => '811'),
                    '12' => array('name' => 'Өлзийт', 'code' => '12', 'full_code' => '812'),
                    '13' => array('name' => 'Өндөршил', 'code' => '13', 'full_code' => '813'),
                    '14' => array('name' => 'Хулд', 'code' => '14', 'full_code' => '814'),
                    '15' => array('name' => 'Цагаандэлгэр', 'code' => '15', 'full_code' => '815'),
                    '16' => array('name' => 'Эрдэнэдалай', 'code' => '16', 'full_code' => '816'),
                ),
            ),
            '9' => array(
                'name' => 'Завхан',
                'code' => '9',
                'sub_branches' => array(
                    '1' => array('name' => 'Алдархаан', 'code' => '1', 'full_code' => '901'),
                    '2' => array('name' => 'Асгат', 'code' => '2', 'full_code' => '902'),
                    '3' => array('name' => 'Баянтэс', 'code' => '3', 'full_code' => '903'),
                    '4' => array('name' => 'Баянхайрхан', 'code' => '4', 'full_code' => '904'),
                    '6' => array('name' => 'Дөрвөлжин', 'code' => '6', 'full_code' => '906'),
                    '7' => array('name' => 'Идэр', 'code' => '7', 'full_code' => '907'),
                    '8' => array('name' => 'Их-Уул', 'code' => '8', 'full_code' => '908'),
                    '9' => array('name' => 'Нөмрөг', 'code' => '9', 'full_code' => '909'),
                    '10' => array('name' => 'Отгон', 'code' => '10', 'full_code' => '910'),
                    '11' => array('name' => 'Сантмаргац', 'code' => '11', 'full_code' => '911'),
                    '12' => array('name' => 'Сонгино', 'code' => '12', 'full_code' => '912'),
                    '13' => array('name' => 'Түдэвтэй', 'code' => '13', 'full_code' => '913'),
                    '14' => array('name' => 'Тэс', 'code' => '14', 'full_code' => '914'),
                    '15' => array('name' => 'Тэлмэн', 'code' => '15', 'full_code' => '915'),
                    '16' => array('name' => 'Улиастай', 'code' => '16', 'full_code' => '916'),
                    '17' => array('name' => 'Цагаанхайрхан', 'code' => '17', 'full_code' => '917'),
                    '18' => array('name' => 'Цагаанчулуут', 'code' => '18', 'full_code' => '918'),
                    '19' => array('name' => 'Цэцэн-Уул', 'code' => '19', 'full_code' => '919'),
                    '20' => array('name' => 'Шилүүстэй', 'code' => '20', 'full_code' => '920'),
                    '21' => array('name' => 'Эрдэнэхайрхан', 'code' => '21', 'full_code' => '921'),
                    '22' => array('name' => 'Яруу', 'code' => '22', 'full_code' => '922'),
                    '23' => array('name' => 'Завханмандал', 'code' => '23', 'full_code' => '923'),
                    '24' => array('name' => 'Ургамал', 'code' => '24', 'full_code' => '924'),
                    '5' => array('name' => 'Тосонцэнгэл', 'code' => '5', 'full_code' => '905'),
                ),
            ),
            '10' => array(
                'name' => 'Өвөрхангай',
                'code' => '10',
                'sub_branches' => array(
                    '1' => array('name' => 'Баян-Өндөр', 'code' => '1', 'full_code' => '1001'),
                    '2' => array('name' => 'Бүрд', 'code' => '2', 'full_code' => '1002'),
                    '3' => array('name' => 'Бат-Өлзий', 'code' => '3', 'full_code' => '1003'),
                    '4' => array('name' => 'Баруунбаян-Улаан', 'code' => '4', 'full_code' => '1004'),
                    '5' => array('name' => 'Баянгол', 'code' => '5', 'full_code' => '1005'),
                    '6' => array('name' => 'Гучин-Ус', 'code' => '6', 'full_code' => '1006'),
                    '7' => array('name' => 'Есөн зүйл', 'code' => '7', 'full_code' => '1007'),
                    '8' => array('name' => 'Өлзийт', 'code' => '8', 'full_code' => '1008'),
                    '9' => array('name' => 'Зүүнбаян-Улаан', 'code' => '9', 'full_code' => '1009'),
                    '10' => array('name' => 'Хайрхандулаан', 'code' => '10', 'full_code' => '1010'),
                    '11' => array('name' => 'Нарийнтээл', 'code' => '11', 'full_code' => '1011'),
                    '12' => array('name' => 'Сант', 'code' => '12', 'full_code' => '1012'),
                    '13' => array('name' => 'Тарагт', 'code' => '13', 'full_code' => '1013'),
                    '14' => array('name' => 'Төгрөг', 'code' => '14', 'full_code' => '1014'),
                    '15' => array('name' => 'Уянга', 'code' => '15', 'full_code' => '1015'),
                    '16' => array('name' => 'Богд', 'code' => '16', 'full_code' => '1016'),
                    '17' => array('name' => 'Хужирт', 'code' => '17', 'full_code' => '1017'),
                    '18' => array('name' => 'Хархорин', 'code' => '18', 'full_code' => '1018'),
                    '19' => array('name' => 'Арвайхээр', 'code' => '19', 'full_code' => '1019'),
                ),
            ),
            '11' => array(
                'name' => 'Өмнөговь',
                'code' => '11',
                'sub_branches' => array(
                    '1' => array('name' => 'Баяндалай', 'code' => '1', 'full_code' => '1101'),
                    '2' => array('name' => 'Баян-Овоо', 'code' => '2', 'full_code' => '1102'),
                    '3' => array('name' => 'Булган', 'code' => '3', 'full_code' => '1103'),
                    '4' => array('name' => 'Гурвантэс', 'code' => '4', 'full_code' => '1104'),
                    '5' => array('name' => 'Мандал-Овоо', 'code' => '5', 'full_code' => '1105'),
                    '6' => array('name' => 'Манлай', 'code' => '6', 'full_code' => '1106'),
                    '7' => array('name' => 'Номгон', 'code' => '7', 'full_code' => '1107'),
                    '8' => array('name' => 'Ноён', 'code' => '8', 'full_code' => '1108'),
                    '9' => array('name' => 'Ханбогд', 'code' => '9', 'full_code' => '1109'),
                    '10' => array('name' => 'Ханхонгор', 'code' => '10', 'full_code' => '1110'),
                    '11' => array('name' => 'Хүрмэн', 'code' => '11', 'full_code' => '1111'),
                    '12' => array('name' => 'Сэврэй', 'code' => '12', 'full_code' => '1112'),
                    '13' => array('name' => 'Цогт-Овоо', 'code' => '13', 'full_code' => '1113'),
                    '14' => array('name' => 'Цогтцэций', 'code' => '14', 'full_code' => '1114'),
                    '15' => array('name' => 'Даланзадгад', 'code' => '15', 'full_code' => '1115'),
                ),
            ),
            '12' => array(
                'name' => 'Сүхбаатар',
                'code' => '12',
                'sub_branches' => array(
                    '10' => array('name' => 'Уулбаян', 'code' => '10', 'full_code' => '1210'),
                    '11' => array('name' => 'Халзан', 'code' => '11', 'full_code' => '1211'),
                    '12' => array('name' => 'Эрдэнэцагаан', 'code' => '12', 'full_code' => '1212'),
                    '14' => array('name' => 'Баруун-Урт', 'code' => '14', 'full_code' => '1214'),
                    '1' => array('name' => 'Асгат', 'code' => '1', 'full_code' => '1201'),
                    '2' => array('name' => 'Баяндэлгэр', 'code' => '2', 'full_code' => '1202'),
                    '3' => array('name' => 'Дарьганга', 'code' => '3', 'full_code' => '1203'),
                    '4' => array('name' => 'Мөнххаан', 'code' => '4', 'full_code' => '1204'),
                    '5' => array('name' => 'Наран', 'code' => '5', 'full_code' => '1205'),
                    '6' => array('name' => 'Онгон', 'code' => '6', 'full_code' => '1206'),
                    '7' => array('name' => 'Сүхбаатар', 'code' => '7', 'full_code' => '1207'),
                    '8' => array('name' => 'Түвшинширээ', 'code' => '8', 'full_code' => '1208'),
                    '9' => array('name' => 'Түмэнцогт', 'code' => '9', 'full_code' => '1209'),
                ),
            ),
            '13' => array(
                'name' => 'Сэлэнгэ',
                'code' => '13',
                'sub_branches' => array(
                    '1' => array('name' => 'Сүхбаатар', 'code' => '1', 'full_code' => '1301'),
                    '2' => array('name' => 'Алтанбулаг', 'code' => '2', 'full_code' => '1302'),
                    '3' => array('name' => 'Цагааннуур', 'code' => '3', 'full_code' => '1303'),
                    '4' => array('name' => 'Орхон', 'code' => '4', 'full_code' => '1304'),
                    '5' => array('name' => 'Шаамар', 'code' => '5', 'full_code' => '1305'),
                    '7' => array('name' => 'Баруунбүрэн', 'code' => '7', 'full_code' => '1307'),
                    '8' => array('name' => 'Сант', 'code' => '8', 'full_code' => '1308'),
                    '9' => array('name' => 'Орхонтуул', 'code' => '9', 'full_code' => '1309'),
                    '10' => array('name' => 'Ерөө', 'code' => '10', 'full_code' => '1310'),
                    '11' => array('name' => 'Зүүнбүрэн', 'code' => '11', 'full_code' => '1311'),
                    '12' => array('name' => 'Баянгол', 'code' => '12', 'full_code' => '1312'),
                    '13' => array('name' => 'Хушаат', 'code' => '13', 'full_code' => '1313'),
                    '14' => array('name' => 'Мандал', 'code' => '14', 'full_code' => '1314'),
                    '15' => array('name' => 'Жавхлант', 'code' => '15', 'full_code' => '1315'),
                    '16' => array('name' => 'Сайхан', 'code' => '16', 'full_code' => '1316'),
                    '19' => array('name' => 'Түшиг', 'code' => '19', 'full_code' => '1319'),
                    '21' => array('name' => 'Хүдэр', 'code' => '21', 'full_code' => '1321'),
                ),
            ),
            '14' => array(
                'name' => 'Төв',
                'code' => '14',
                'sub_branches' => array(
                    '1' => array('name' => 'Алтанбулаг', 'code' => '1', 'full_code' => '1401'),
                    '2' => array('name' => 'Аргалант', 'code' => '2', 'full_code' => '1402'),
                    '3' => array('name' => 'Архуст', 'code' => '3', 'full_code' => '1403'),
                    '4' => array('name' => 'Батсүмбэр', 'code' => '4', 'full_code' => '1404'),
                    '5' => array('name' => 'Баян', 'code' => '5', 'full_code' => '1405'),
                    '6' => array('name' => 'Баян-Өнжүүл', 'code' => '6', 'full_code' => '1406'),
                    '7' => array('name' => 'Баяндэлгэр', 'code' => '7', 'full_code' => '1407'),
                    '8' => array('name' => 'Баянжаргалан', 'code' => '8', 'full_code' => '1408'),
                    '9' => array('name' => 'Баянхангай', 'code' => '9', 'full_code' => '1409'),
                    '10' => array('name' => 'Баянчандмань', 'code' => '10', 'full_code' => '1410'),
                    '11' => array('name' => 'Баянцагаан', 'code' => '11', 'full_code' => '1411'),
                    '12' => array('name' => 'Баянцогт', 'code' => '12', 'full_code' => '1412'),
                    '13' => array('name' => 'Борнуур', 'code' => '13', 'full_code' => '1413'),
                    '14' => array('name' => 'Бүрэн', 'code' => '14', 'full_code' => '1414'),
                    '15' => array('name' => 'Дэлгэрхаан', 'code' => '15', 'full_code' => '1415'),
                    '16' => array('name' => 'Жаргалант', 'code' => '16', 'full_code' => '1416'),
                    '17' => array('name' => 'Заамар', 'code' => '17', 'full_code' => '1417'),
                    '18' => array('name' => 'Лүн', 'code' => '18', 'full_code' => '1418'),
                    '19' => array('name' => 'Мөнгөнморьт', 'code' => '19', 'full_code' => '1419'),
                    '20' => array('name' => 'Өндөрширээт', 'code' => '20', 'full_code' => '1420'),
                    '21' => array('name' => 'Сэргэлэн', 'code' => '21', 'full_code' => '1421'),
                    '22' => array('name' => 'Сүмбэр', 'code' => '22', 'full_code' => '1422'),
                    '23' => array('name' => 'Угтаалцайдам', 'code' => '23', 'full_code' => '1423'),
                    '24' => array('name' => 'Цээл', 'code' => '24', 'full_code' => '1424'),
                    '25' => array('name' => 'Эрдэнэ', 'code' => '25', 'full_code' => '1425'),
                    '26' => array('name' => 'Эрдэнэсант', 'code' => '26', 'full_code' => '1426'),
                    '27' => array('name' => 'Зуунмод', 'code' => '27', 'full_code' => '1427'),
                ),
            ),
            '15' => array(
                'name' => 'Увс',
                'code' => '15',
                'sub_branches' => array(
                    '1' => array('name' => 'Баруунтуруун', 'code' => '1', 'full_code' => '1501'),
                    '2' => array('name' => 'Бөхмөрөн', 'code' => '2', 'full_code' => '1502'),
                    '3' => array('name' => 'Давст', 'code' => '3', 'full_code' => '1503'),
                    '4' => array('name' => 'Завхан', 'code' => '4', 'full_code' => '1504'),
                    '5' => array('name' => 'Зүүнговь', 'code' => '5', 'full_code' => '1505'),
                    '6' => array('name' => 'Зүүнхангай', 'code' => '6', 'full_code' => '1506'),
                    '7' => array('name' => 'Малчин', 'code' => '7', 'full_code' => '1507'),
                    '8' => array('name' => 'Наранбулаг', 'code' => '8', 'full_code' => '1508'),
                    '9' => array('name' => 'Өлгий', 'code' => '9', 'full_code' => '1509'),
                    '10' => array('name' => 'Өмнөговь', 'code' => '10', 'full_code' => '1510'),
                    '11' => array('name' => 'Өндөрхангай', 'code' => '11', 'full_code' => '1511'),
                    '12' => array('name' => 'Сагил', 'code' => '12', 'full_code' => '1512'),
                    '13' => array('name' => 'Тариалан', 'code' => '13', 'full_code' => '1513'),
                    '14' => array('name' => 'Түргэн', 'code' => '14', 'full_code' => '1514'),
                    '15' => array('name' => 'Тэс', 'code' => '15', 'full_code' => '1515'),
                    '17' => array('name' => 'Ховд', 'code' => '17', 'full_code' => '1517'),
                    '18' => array('name' => 'Хяргас', 'code' => '18', 'full_code' => '1518'),
                    '19' => array('name' => 'Цагаанхайрхан', 'code' => '19', 'full_code' => '1519'),
                    '20' => array('name' => 'Улаангом', 'code' => '20', 'full_code' => '1520'),
                ),
            ),
            '16' => array(
                'name' => 'Ховд',
                'code' => '16',
                'sub_branches' => array(
                    '1' => array('name' => 'Алтай', 'code' => '1', 'full_code' => '1601'),
                    '2' => array('name' => 'Булган', 'code' => '2', 'full_code' => '1602'),
                    '3' => array('name' => 'Буянт', 'code' => '3', 'full_code' => '1603'),
                    '4' => array('name' => 'Дарви', 'code' => '4', 'full_code' => '1604'),
                    '5' => array('name' => 'Дуут', 'code' => '5', 'full_code' => '1605'),
                    '6' => array('name' => 'Дөргөн', 'code' => '6', 'full_code' => '1606'),
                    '7' => array('name' => 'Зэрэг', 'code' => '7', 'full_code' => '1607'),
                    '8' => array('name' => 'Манхан', 'code' => '8', 'full_code' => '1608'),
                    '9' => array('name' => 'Мөст', 'code' => '9', 'full_code' => '1609'),
                    '10' => array('name' => 'Мянгад', 'code' => '10', 'full_code' => '1610'),
                    '11' => array('name' => 'Мөнххайрхан', 'code' => '11', 'full_code' => '1611'),
                    '12' => array('name' => 'Үенч', 'code' => '12', 'full_code' => '1612'),
                    '13' => array('name' => 'Ховд', 'code' => '13', 'full_code' => '1613'),
                    '14' => array('name' => 'Цэцэг', 'code' => '14', 'full_code' => '1614'),
                    '15' => array('name' => 'Чандмань', 'code' => '15', 'full_code' => '1615'),
                    '16' => array('name' => 'Эрдэнэбүрэн', 'code' => '16', 'full_code' => '1616'),
                    '17' => array('name' => 'Жаргалант', 'code' => '17', 'full_code' => '1617'),
                ),
            ),
            '17' => array(
                'name' => 'Хөвсгөл',
                'code' => '17',
                'sub_branches' => array(
                    '1' => array('name' => 'Алаг-Эрдэнэ', 'code' => '1', 'full_code' => '1701'),
                    '2' => array('name' => 'Арбулаг', 'code' => '2', 'full_code' => '1702'),
                    '3' => array('name' => 'Баянзүрх', 'code' => '3', 'full_code' => '1703'),
                    '4' => array('name' => 'Бүрэнтогтох', 'code' => '4', 'full_code' => '1704'),
                    '5' => array('name' => 'Галт', 'code' => '5', 'full_code' => '1705'),
                    '6' => array('name' => 'Жаргалант', 'code' => '6', 'full_code' => '1706'),
                    '7' => array('name' => 'Их-Уул', 'code' => '7', 'full_code' => '1707'),
                    '8' => array('name' => 'Рашаант', 'code' => '8', 'full_code' => '1708'),
                    '9' => array('name' => 'Рэнчинлхүмбэ', 'code' => '9', 'full_code' => '1709'),
                    '10' => array('name' => 'Тариалан', 'code' => '10', 'full_code' => '1710'),
                    '11' => array('name' => 'Тосонцэнгэл', 'code' => '11', 'full_code' => '1711'),
                    '12' => array('name' => 'Төмөрбулаг', 'code' => '12', 'full_code' => '1712'),
                    '13' => array('name' => 'Түнэл', 'code' => '13', 'full_code' => '1713'),
                    '14' => array('name' => 'Улаан-Уул', 'code' => '14', 'full_code' => '1714'),
                    '15' => array('name' => 'Ханх', 'code' => '15', 'full_code' => '1715'),
                    '17' => array('name' => 'Цагаан-Уул', 'code' => '17', 'full_code' => '1717'),
                    '18' => array('name' => 'Цагаан-Үүр', 'code' => '18', 'full_code' => '1718'),
                    '19' => array('name' => 'Цагааннуур', 'code' => '19', 'full_code' => '1719'),
                    '20' => array('name' => 'Цэцэрлэг', 'code' => '20', 'full_code' => '1720'),
                    '21' => array('name' => 'Чандмань-Өндөр', 'code' => '21', 'full_code' => '1721'),
                    '22' => array('name' => 'Шинэ-Идэр', 'code' => '22', 'full_code' => '1722'),
                    '23' => array('name' => 'Эрдэнэбулган', 'code' => '23', 'full_code' => '1723'),
                    '24' => array('name' => 'Мөрөн', 'code' => '24', 'full_code' => '1724'),
                ),
            ),
            '18' => array(
                'name' => 'Хэнтий',
                'code' => '18',
                'sub_branches' => array(
                    '1' => array('name' => 'Галшар', 'code' => '1', 'full_code' => '1801'),
                    '2' => array('name' => 'Баянхутаг', 'code' => '2', 'full_code' => '1802'),
                    '3' => array('name' => 'Баянмөнх', 'code' => '3', 'full_code' => '1803'),
                    '4' => array('name' => 'Дархан', 'code' => '4', 'full_code' => '1804'),
                    '5' => array('name' => 'Дэлгэрхаан', 'code' => '5', 'full_code' => '1805'),
                    '6' => array('name' => 'Жаргалтхаан', 'code' => '6', 'full_code' => '1806'),
                    '7' => array('name' => 'Цэнхэрмандал', 'code' => '7', 'full_code' => '1807'),
                    '8' => array('name' => 'Өмнөдэлгэр', 'code' => '8', 'full_code' => '1808'),
                    '9' => array('name' => 'Батширээт', 'code' => '9', 'full_code' => '1809'),
                    '10' => array('name' => 'Биндэр', 'code' => '10', 'full_code' => '1810'),
                    '11' => array('name' => 'Баян-Адарга', 'code' => '11', 'full_code' => '1811'),
                    '12' => array('name' => 'Дадал', 'code' => '12', 'full_code' => '1812'),
                    '13' => array('name' => 'Норовлин', 'code' => '13', 'full_code' => '1813'),
                    '14' => array('name' => 'Батноров', 'code' => '14', 'full_code' => '1814'),
                    '15' => array('name' => 'Баян-Овоо', 'code' => '15', 'full_code' => '1815'),
                    '16' => array('name' => 'Мөрөн', 'code' => '16', 'full_code' => '1816'),
                    '17' => array('name' => 'Хэрлэн', 'code' => '17', 'full_code' => '1817'),
                    '24' => array('name' => 'Бор-Өндөр', 'code' => '24', 'full_code' => '1824'),
                ),
            ),
            '19' => array(
                'name' => 'Дархан-Уул',
                'code' => '19',
                'sub_branches' => array(
                    '1' => array('name' => 'Дархан', 'code' => '1', 'full_code' => '1901'),
                    '2' => array('name' => 'Шарын гол', 'code' => '2', 'full_code' => '1902'),
                    '3' => array('name' => 'Хонгор', 'code' => '3', 'full_code' => '1903'),
                    '4' => array('name' => 'Орхон', 'code' => '4', 'full_code' => '1904'),
                ),
            ),
            '20' => array(
                'name' => 'Орхон',
                'code' => '20',
                'sub_branches' => array(
                    '1' => array('name' => 'Баян-Өндөр', 'code' => '1', 'full_code' => '2001'),
                    '2' => array('name' => 'Жаргалант', 'code' => '2', 'full_code' => '2002'),
                ),
            ),
            '23' => array(
                'name' => 'Хан-Уул',
                'code' => '23',
                'sub_branches' => array(
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '2301'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '2302'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '2303'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '2304'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '2305'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '2306'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '2307'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '2308'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '2309'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '2310'),
                    '11' => array('name' => '11-р хороо', 'code' => '11', 'full_code' => '2311'),
                    '12' => array('name' => '12-р хороо', 'code' => '12', 'full_code' => '2312'),
                    '13' => array('name' => '13-рхороо', 'code' => '13', 'full_code' => '2313'),
                    '14' => array('name' => '14-р хороо', 'code' => '14', 'full_code' => '2314'),
                    '15' => array('name' => '15-р хороо', 'code' => '15', 'full_code' => '2315'),
                    '16' => array('name' => '16-р хороо', 'code' => '16', 'full_code' => '2316'),
                    '17' => array('name' => '17-р хороо', 'code' => '17', 'full_code' => '2317'),
                    '18' => array('name' => '18-р хороо', 'code' => '18', 'full_code' => '2318'),
                    '19' => array('name' => '19-р хороо', 'code' => '19', 'full_code' => '2319'),
                    '20' => array('name' => '20-р хороо', 'code' => '20', 'full_code' => '2320'),
                ),
            ),
            '24' => array(
                'name' => 'Баянзүрх',
                'code' => '24',
                'sub_branches' => array(
                    '21' => array('name' => '21-р хороо', 'code' => '21', 'full_code' => '2421'),
                    '22' => array('name' => '22-р хороо', 'code' => '22', 'full_code' => '2422'),
                    '23' => array('name' => '23-р хороо', 'code' => '23', 'full_code' => '2423'),
                    '24' => array('name' => '24-р хороо', 'code' => '24', 'full_code' => '2424'),
                    '25' => array('name' => '25-р хороо', 'code' => '25', 'full_code' => '2425'),
                    '26' => array('name' => '26-р хороо', 'code' => '26', 'full_code' => '2426'),
                    '27' => array('name' => '27-р хороо', 'code' => '27', 'full_code' => '2427'),
                    '28' => array('name' => '28-р хороо', 'code' => '28', 'full_code' => '2428'),
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '2401'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '2402'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '2403'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '2404'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '2405'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '2406'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '2407'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '2408'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '2409'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '2410'),
                    '11' => array('name' => '11-р хороо', 'code' => '11', 'full_code' => '2411'),
                    '12' => array('name' => '12-р хороо', 'code' => '12', 'full_code' => '2412'),
                    '13' => array('name' => '13-р хороо', 'code' => '13', 'full_code' => '2413'),
                    '14' => array('name' => '14-р хороо', 'code' => '14', 'full_code' => '2414'),
                    '15' => array('name' => '15-р хороо', 'code' => '15', 'full_code' => '2415'),
                    '16' => array('name' => '16-р хороо', 'code' => '16', 'full_code' => '2416'),
                    '17' => array('name' => '17-р хороо', 'code' => '17', 'full_code' => '2417'),
                    '18' => array('name' => '18-р хороо', 'code' => '18', 'full_code' => '2418'),
                    '19' => array('name' => '19-р хороо', 'code' => '19', 'full_code' => '2419'),
                    '20' => array('name' => '20-р хороо', 'code' => '20', 'full_code' => '2420'),
                ),
            ),
            '25' => array(
                'name' => 'Сүхбаатар дүүрэг',
                'code' => '25',
                'sub_branches' => array(
                    '21' => array('name' => '21-р хороо', 'code' => '21', 'full_code' => '2521'),
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '2501'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '2502'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '2503'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '2504'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '2505'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '2506'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '2507'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '2508'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '2509'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '2510'),
                    '11' => array('name' => '11-р хороо', 'code' => '11', 'full_code' => '2511'),
                    '12' => array('name' => '12-р хороо', 'code' => '12', 'full_code' => '2512'),
                    '13' => array('name' => '13-р хороо', 'code' => '13', 'full_code' => '2513'),
                    '14' => array('name' => '14-р хороо', 'code' => '14', 'full_code' => '2514'),
                    '15' => array('name' => '15-р хороо', 'code' => '15', 'full_code' => '2515'),
                    '16' => array('name' => '16-р хороо', 'code' => '16', 'full_code' => '2516'),
                    '17' => array('name' => '17-р хороо', 'code' => '17', 'full_code' => '2517'),
                    '18' => array('name' => '18-р хороо', 'code' => '18', 'full_code' => '2518'),
                    '19' => array('name' => '19-р хороо', 'code' => '19', 'full_code' => '2519'),
                    '20' => array('name' => '20-р хороо', 'code' => '20', 'full_code' => '2520'),
                ),
            ),
            '26' => array(
                'name' => 'Баянгол',
                'code' => '26',
                'sub_branches' => array(
                    '21' => array('name' => '21-р хороо', 'code' => '21', 'full_code' => '2621'),
                    '22' => array('name' => '22-р хороо', 'code' => '22', 'full_code' => '2622'),
                    '23' => array('name' => '23-р хороо', 'code' => '23', 'full_code' => '2623'),
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '2601'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '2602'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '2603'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '2604'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '2605'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '2606'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '2607'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '2608'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '2609'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '2610'),
                    '11' => array('name' => '11-р хороо', 'code' => '11', 'full_code' => '2611'),
                    '12' => array('name' => '12-р хороо', 'code' => '12', 'full_code' => '2612'),
                    '13' => array('name' => '13-р хороо', 'code' => '13', 'full_code' => '2613'),
                    '14' => array('name' => '14-р хороо', 'code' => '14', 'full_code' => '2614'),
                    '15' => array('name' => '15-р хороо', 'code' => '15', 'full_code' => '2615'),
                    '16' => array('name' => '16-р хороо', 'code' => '16', 'full_code' => '2616'),
                    '17' => array('name' => '17-р хороо', 'code' => '17', 'full_code' => '2617'),
                    '18' => array('name' => '18-р хороо', 'code' => '18', 'full_code' => '2618'),
                    '19' => array('name' => '19-р хороо', 'code' => '19', 'full_code' => '2619'),
                    '20' => array('name' => '20-р хороо', 'code' => '20', 'full_code' => '2620'),
                ),
            ),
            '27' => array(
                'name' => 'Багануур',
                'code' => '27',
                'sub_branches' => array(
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '2701'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '2702'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '2703'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '2704'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '2705'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '2706'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '2707'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '2708'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '2709'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '2710'),
                ),
            ),
            '28' => array(
                'name' => 'Багахангай',
                'code' => '28',
                'sub_branches' => array(
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '2801'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '2802'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '2803'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '2804'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '2805'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '2806'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '2807'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '2808'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '2809'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '2810'),
                ),
            ),
            '29' => array(
                'name' => 'Налайх',
                'code' => '29',
                'sub_branches' => array(
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '2901'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '2902'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '2903'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '2904'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '2905'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '2906'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '2907'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '2908'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '2909'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '2910'),
                ),
            ),
            '32' => array(
                'name' => 'Говьсүмбэр',
                'code' => '32',
                'sub_branches' => array(
                    '1' => array('name' => 'Сүмбэр', 'code' => '1', 'full_code' => '3201'),
                    '2' => array('name' => 'Баянтал', 'code' => '2', 'full_code' => '3202'),
                    '3' => array('name' => 'Шивээговь', 'code' => '3', 'full_code' => '3203'),
                ),
            ),
            '34' => array(
                'name' => 'Сонгинохайрхан',
                'code' => '34',
                'sub_branches' => array(
                    '20' => array('name' => '20-р хороо', 'code' => '20', 'full_code' => '3420'),
                    '21' => array('name' => '21-р хороо', 'code' => '21', 'full_code' => '3421'),
                    '22' => array('name' => '22-р хороо', 'code' => '22', 'full_code' => '3422'),
                    '23' => array('name' => '23-р хороо', 'code' => '23', 'full_code' => '3423'),
                    '24' => array('name' => '24-р хороо', 'code' => '24', 'full_code' => '3424'),
                    '25' => array('name' => '25-р хороо', 'code' => '25', 'full_code' => '3425'),
                    '28' => array('name' => '28-р хороо', 'code' => '28', 'full_code' => '3428'),
                    '29' => array('name' => '29-р хороо', 'code' => '29', 'full_code' => '3429'),
                    '30' => array('name' => '30-р хороо', 'code' => '30', 'full_code' => '3430'),
                    '31' => array('name' => '31-р хороо', 'code' => '31', 'full_code' => '3431'),
                    '32' => array('name' => '32-р хороо', 'code' => '32', 'full_code' => '3432'),
                    '26' => array('name' => '26-р хороо', 'code' => '26', 'full_code' => '3426'),
                    '27' => array('name' => '27-р хороо', 'code' => '27', 'full_code' => '3427'),
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '3401'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '3402'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '3403'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '3404'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '3405'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '3406'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '3407'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '3408'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '3409'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '3410'),
                    '11' => array('name' => '11-р хороо', 'code' => '11', 'full_code' => '3411'),
                    '12' => array('name' => '12-р хороо', 'code' => '12', 'full_code' => '3412'),
                    '13' => array('name' => '13-р хороо', 'code' => '13', 'full_code' => '3413'),
                    '14' => array('name' => '14-р хороо', 'code' => '14', 'full_code' => '3414'),
                    '15' => array('name' => '15-р хороо', 'code' => '15', 'full_code' => '3415'),
                    '16' => array('name' => '16-р хороо', 'code' => '16', 'full_code' => '3416'),
                    '17' => array('name' => '17-р хороо', 'code' => '17', 'full_code' => '3417'),
                    '18' => array('name' => '18-р хороо', 'code' => '18', 'full_code' => '3418'),
                    '19' => array('name' => '19-р хороо', 'code' => '19', 'full_code' => '3419'),
                ),
            ),
            '35' => array(
                'name' => 'Чингэлтэй',
                'code' => '35',
                'sub_branches' => array(
                    '1' => array('name' => '1-р хороо', 'code' => '1', 'full_code' => '3501'),
                    '2' => array('name' => '2-р хороо', 'code' => '2', 'full_code' => '3502'),
                    '3' => array('name' => '3-р хороо', 'code' => '3', 'full_code' => '3503'),
                    '4' => array('name' => '4-р хороо', 'code' => '4', 'full_code' => '3504'),
                    '5' => array('name' => '5-р хороо', 'code' => '5', 'full_code' => '3505'),
                    '6' => array('name' => '6-р хороо', 'code' => '6', 'full_code' => '3506'),
                    '7' => array('name' => '7-р хороо', 'code' => '7', 'full_code' => '3507'),
                    '8' => array('name' => '8-р хороо', 'code' => '8', 'full_code' => '3508'),
                    '9' => array('name' => '9-р хороо', 'code' => '9', 'full_code' => '3509'),
                    '10' => array('name' => '10-р хороо', 'code' => '10', 'full_code' => '3510'),
                    '11' => array('name' => '11-р хороо', 'code' => '11', 'full_code' => '3511'),
                    '12' => array('name' => '12-р хороо', 'code' => '12', 'full_code' => '3512'),
                    '13' => array('name' => '13-р хороо', 'code' => '13', 'full_code' => '3513'),
                    '14' => array('name' => '14-р хороо', 'code' => '14', 'full_code' => '3514'),
                    '15' => array('name' => '15-р хороо', 'code' => '15', 'full_code' => '3515'),
                    '16' => array('name' => '16-р хороо', 'code' => '16', 'full_code' => '3516'),
                    '17' => array('name' => '17-р хороо', 'code' => '17', 'full_code' => '3517'),
                    '18' => array('name' => '18-р хороо', 'code' => '18', 'full_code' => '3518'),
                    '19' => array('name' => '19-р хороо', 'code' => '19', 'full_code' => '3519'),
                    '20' => array('name' => '20-р хороо', 'code' => '20', 'full_code' => '3520'),
                ),
            ),
        );
    }

    /**
     * VAT zero-rated codes (0%)
     * @return array
     */
    public static function get_vat_zero_data() {
        return array(
            '501' => array('code' => '501', 'name' => 'Монгол Улсын нутаг дэвсгэрээс экспортод гаргасан, гаалийн байгууллагад мэдүүлсэн бараа', 'type' => 'zero'),
            '502' => array('code' => '502', 'name' => 'Монгол Улсын Олон улсын гэрээнд заасны дагуу Монгол Улсаас гадаад улсад, гадаад улсаас Монгол Улс хүртэл, түүнчлэн гадаад улсаас Монгол Улсын хилээр дамжуулан бусад улсад гаргасан олон улсын зорчигч болон ачаа тээврийн үйлчилгээ', 'type' => 'zero'),
            '503' => array('code' => '503', 'name' => 'Монгол Улсын нутаг дэвсгэрээс гадна үзүүлсэн /албан татвараас чөлөөлсөн үйлчилгээг оролцуулан/ үйлчилгээ', 'type' => 'zero'),
            '504' => array('code' => '504', 'name' => 'Монгол Улсад оршин суугч бус этгээдэд үзүүлсэн үйлчилгээ /түүний дотор албан татвараас чөлөөлсөн үйлчилгээг оролцуулан/', 'type' => 'zero'),
            '505' => array('code' => '505', 'name' => 'Олон улсын нислэг үйлдэж байгаа дотоодын болон гадаадын агаарын тээврийн хөлөгт үзүүлэх нислэгийн хөдөлгөөний удирдлага, техникийн болон шатахууны үйлчилгээ, цэвэрлэгээ, нислэгийн явцад нисэх бүрэлдэхүүн, зорчигчдод худалдаа, хоол, ундаагаар үйлчилсэн үйлчилгээ', 'type' => 'zero'),
            '506' => array('code' => '506', 'name' => 'Засгийн газар, Монголбанкны захиалгаар дотоодод үйлдвэрлэсэн төрийн одон медаль, мөнгөн тэмдэгт, зоос', 'type' => 'zero'),
            '507' => array('code' => '507', 'name' => 'Ашигт малтмалын эцсийн бүтээгдэхүүн', 'type' => 'zero'),
        );
    }

    /**
     * VAT exempt codes
     * @return array
     */
    public static function get_vat_exempt_data() {
        return array(
            '305' => array('code' => '305', 'name' => 'Хөгжлийн бэрхшээлтэй иргэний хэрэглээнд зориулсан тусгай зориулалтын хэрэгсэл, тоног төхөөрөмж, автотээврийн хэрэгсэл', 'type' => 'exempt'),
            '307' => array('code' => '307', 'name' => 'Иргэний агаарын хөлөг, хөдөлгүүр болон газар дээрх дадлагажуур, тэдгээрийн эд анги, бүрэлдэхүүн хэсэг, дэд угсралтын хэсэг, сэлбэг, тоног төхөөрөмж, холбогдох хэрэгсэл', 'type' => 'exempt'),
            '308' => array('code' => '308', 'name' => 'Орон сууцны зориулалтаар ашиглаж байгаа байр буюу түүний хэсгийг борлуулсны орлого', 'type' => 'exempt'),
            '310' => array('code' => '310', 'name' => 'Эмчилгээний зориулалтаар хэрэглэх цус, цусан бүтээгдэхүүн, эд эрхтэн', 'type' => 'exempt'),
            '311' => array('code' => '311', 'name' => 'Хийн түлш, түүний сав, тоног төхөөрөмж, тусгай зориулалтын машин механизм, техник хэрэгсэл, тоноглол', 'type' => 'exempt'),
            '313' => array('code' => '313', 'name' => 'Борлуулсан алт', 'type' => 'exempt'),
            '315' => array('code' => '315', 'name' => 'Эрдэм шинжилгээ, судалгааны ажлын туршилтын бүтээгдэхүүн', 'type' => 'exempt'),
            '318' => array('code' => '318', 'name' => 'Газар тариалан эрхлэгчийн дотооддоо тарьж борлуулсан үр тариа, төмс, хүнсний ногоо, суулгац, жимс жимсгэнэ, үйлдвэрлэсэн гурил', 'type' => 'exempt'),
            '319' => array('code' => '319', 'name' => 'Монгол Улсын нутаг дэвсгэрт үйлдвэрийн аргаар төхөөрч бэлтгэн дотооддоо борлуулсан тураг болон шулж ангилсан мах, боловсруулаагүй дотор эрхтэн, дайвар бүтээгдэхүүн', 'type' => 'exempt'),
            '320' => array('code' => '320', 'name' => 'Монгол Улсын нутаг дэвсгэрт дотоодын түүхий эдээр боловсруулан дотооддоо борлуулсан хүнсний сүү, сүүн бүтээгдэхүүн', 'type' => 'exempt'),
            '401' => array('code' => '401', 'name' => 'Валют солих үйлчилгээ', 'type' => 'exempt'),
            '402' => array('code' => '402', 'name' => 'мөнгө хүлээн авах, шилжүүлэх, баталгаа, төлбөрийн нэхэмжлэл гаргах, вексель, хадгаламжийн данстай холбогдсон банкны үйлчилгээ', 'type' => 'exempt'),
            '403' => array('code' => '403', 'name' => 'Даатгал, даатгалын зуучлал, давхар даатгал, эд хөрөнгийн бүртгэлийн үйлчилгээ', 'type' => 'exempt'),
            '404' => array('code' => '404', 'name' => 'Үнэт цаас, хувьцаа гаргах, шилжүүлэх, борлуулах, хүлээн авах, тэдгээрт баталгаа гаргах үйлчилгээ', 'type' => 'exempt'),
            '405' => array('code' => '405', 'name' => 'Зээл олгох үйлчилгээ', 'type' => 'exempt'),
            '406' => array('code' => '406', 'name' => 'Нийгмийн болон эрүүл мэндийн даатгалын сангийн мөнгөн хөрөнгийг байршуулсны хүүг олгох, шилжүүлэх үйлчилгээ', 'type' => 'exempt'),
            '407' => array('code' => '407', 'name' => 'Банкны болон банк бус санхүүгийн байгууллага, хадгаламж зээлийн хоршооны зээлийн хүү, Аж ахуйн нэгжийн орлогын албан татварын тухай хуулийн 9.4-т заасан хүү, 10.1.3-т заасан хувьцаа, үнэт цаас, санхүүгийн бусад хэрэгсэл, санхүүгийн түрээсийн хүү, ногдол ашиг, зээлийн баталгааны хураамж, даатгалын гэрээний хураамж төлөх үйлчилгээ', 'type' => 'exempt'),
            '408' => array('code' => '408', 'name' => 'Орон сууцны зориулалтаар баригдсан зориулалтын дагуу ашиглагдаж байгаа байрыг болон түүний тодорхой хэсгийг хөлслүүлэх үйлчилгээ', 'type' => 'exempt'),
            '409' => array('code' => '409', 'name' => 'Боловсролын болон мэргэжлийн сургалт явуулах зөвшөөрөлтэй хувь хүн, хуулийн этгээдийн эрхлэн гүйцэтгэж байгаа дүрэмд нь заасан боловсрол, мэргэжил олгох үйлчилгээ', 'type' => 'exempt'),
            '410' => array('code' => '410', 'name' => 'Эрүүл мэндийн үйлчилгээ', 'type' => 'exempt'),
            '411' => array('code' => '411', 'name' => 'Шашны байгууллагын үйлчилгээ', 'type' => 'exempt'),
            '412' => array('code' => '412', 'name' => 'Төрийн байгууллагаас үзүүлж байгаа үйлчилгээ. Үүнд Засгийн газар, түүний агентлагууд, төсөвт байгууллагуудаас үзүүлж байгаа төрийн үйлчилгээ хамаарна', 'type' => 'exempt'),
            '413' => array('code' => '413', 'name' => 'Автотээврийн тухай хуулийн[6] 3.1.11-д заасан нийтийн тээврийн үйлчилгээ', 'type' => 'exempt'),
            '414' => array('code' => '414', 'name' => 'Тур оператор, аяллын агент гадаад улсын аялал жуулчлалын байгууллагатай гэрээ байгуулж жуулчдыг нь хүлээн авах, уг үйлчилгээг төлөвлөх, сурталчлах, виз авахтай холбогдсон болон аяллын бусад бичиг баримтын бүрдүүлэлт хийх зэрэг гадаадын жуулчинд үзүүлсэн үйлчилгээ', 'type' => 'exempt'),
            '419' => array('code' => '419', 'name' => 'Монгол Улсын нутаг дэвсгэрт үйлдвэрлэсэн, үйлдвэрлэн борлуулсан жижиг, дунд үйлдвэрийн үйлдвэрлэлийн зориулалт бүхий тоног төхөөрөмж, сэлбэг хэрэгсэл', 'type' => 'exempt'),
            '421' => array('code' => '421', 'name' => 'НӨАТ тухай хуулийн 12.1.7-д зааснаас бусад экспортод гаргасан ашигт малтмалын бүтээгдэхүүн', 'type' => 'exempt'),
            '423' => array('code' => '423', 'name' => 'Инновацийн төслөөр дотоод, гадаадын зах зээлд шинэ бараа, бүтээгдэхүүний үйлдвэрлэл явуулахад шаардлагатай, дотоодод үйлдвэрлэдэггүй түүхий эд, материал, урвалж бодис', 'type' => 'exempt'),
            '425' => array('code' => '425', 'name' => 'Экспортод гаргасан түүхий болон угаасан, самнасан ноолуур, арьс шир', 'type' => 'exempt'),
            '426' => array('code' => '426', 'name' => 'Соёлын өвийг судалж шинжлэх, сэргээн засварлахад ашиглах материал, техник, тоног төхөөрөмж, бодис, багаж хэрэгсэл', 'type' => 'exempt'),
            '428' => array('code' => '428', 'name' => 'Газрын тос болон уламжлалт бус газрын тостой холбогдсон тайлан материал, дээж болон газрын тос', 'type' => 'exempt'),
            '429' => array('code' => '429', 'name' => 'Чөлөөт бүсэд зорчигчийн худалдаж авсан гурван сая төгрөг хүртэл үнийн дүнтэй бараа', 'type' => 'exempt'),
            '430' => array('code' => '430', 'name' => 'Соёлын өвийг сэргээн засварлах үйлчилгээ', 'type' => 'exempt'),
            '431' => array('code' => '431', 'name' => 'Оршуулгын үйлчилгээ', 'type' => 'exempt'),
            '433' => array('code' => '433', 'name' => 'Сэргээгдэх эрчим хүчний судалгаа шинжилгээний болон үйлдвэрлэлийн тоног төхөөрөмж, түүний дагалдах хэрэгсэл, сэлбэг.', 'type' => 'exempt'),
            '434' => array('code' => '434', 'name' => 'Импортоор оруулж байгаа болон дотооддоо худалдан борлуулсан хөдөө аж ахуйн зориулалттай шинэ трактор, комбайн, машин механизм, гурилын болон бордооны үйлдвэрийн тоног төхөөрөмж, усалгааны тоног төхөөрөмж, ойн аж ахуйн техник, тоног төхөөрөмж, бордоо, ургамал хамгааллын бодис ', 'type' => 'exempt'),
            '436' => array('code' => '436', 'name' => 'Мал эмнэлэгийн үйлчилгээ', 'type' => 'exempt'),
            '437' => array('code' => '437', 'name' => 'Нотариатын үйлчилгээ', 'type' => 'exempt'),
            '439' => array('code' => '439', 'name' => '“Таван толгой түлш” ХХК-ийн үйлдвэрлэсэн сайжруулсан шахмал түлш', 'type' => 'exempt'),
            '438' => array('code' => '438', 'name' => 'Үнэт цаасны зах зээлийн тухай хуулийн 4.1.6-д заасан санхүүгийн хэрэгслийг анхдагч, хоёрдогч зах зээл болон биржийн бус зах зээлд бүртгүүлэх, гаргах, арилжих, шилжүүлэх, борлуулах, хүлээн авах, хадгалах үйл ажиллагаа болон тэдгээрт баталгаа гаргах үйлчилгээ;', 'type' => 'exempt'),
            '316' => array('code' => '316', 'name' => 'банк, банк бус санхүүгийн байгууллага болон бусад хуулийн этгээдээс банк, тусгай зориулалтын компани, орон сууцны санхүүжилтийн компанид хөрөнгөөр баталгаажсан үнэт цаас гаргах зориулалтаар шилжүүлсэн зээл, санхүүгийн түрээсийн гэрээнээс үүсэх аливаа шаардах эрх;', 'type' => 'exempt'),
            '443' => array('code' => '443', 'name' => 'Ирээдүйн өв санд улсын төсвөөс хуваарилсан орлого эх үүсвэр, сангийн хөрөнгө оруулалтын орлого', 'type' => 'exempt'),
            '444' => array('code' => '444', 'name' => 'Шинээр үйлдвэрлэсэн инновацийн бүтээгдэхүүн, ажил үйлчилгээ', 'type' => 'exempt'),
            '445' => array('code' => '445', 'name' => 'Виртуал хөрөнгийн үйлчилгээ', 'type' => 'exempt'),
            '447' => array('code' => '447', 'name' => 'Малчин, мал бүхий этгээдийн борлуулсан таван хошуу мал, анхан шатны боловсруулалтад ороогүй мах, сүү, арьс шир, ноолуур, хонь болон тэмээний ноос, сарлагийн хөөвөр', 'type' => 'exempt'),
        );
    }

}

// End of file
